name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Pack
      run: dotnet pack --no-build --configuration Release
    - name: Login to GitHub Packages
      run: dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
    - name: Publish
      run: dotnet nuget push "bin/Release/Azure.IoT.Edge.SasTokenHelper.1.0.4.nupkg" --api-key ${{ secrets.TOKEN }} --source "github" --skip-duplicate

